### ISSUE TITLE
Autocomplete different schema oracle

### ISSUE THREAD

**Issue by calope** [mtxr/SQLTools#112]
### Issue Type

* [x] Feature Request - Oracle.
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

I trying to autocomplete the name's column but only works with schema's table.
I trying to change the schema execute this sentence
  ALTER SESSION SET CURRENT_SCHEMA =

But doesn't autocomplete. Only with the schema connection.

### Versions

- *Version*: v0.9.2
- *OS*: All
- *RDBMS*: Oracle

**Comment by tkopets** [comment]
Right now for Oracle we get only identifiers related to the current schema, and this can be easily changed to pull all available identifiers.
The problem with trying to set: `ALTER SESSION SET CURRENT_SCHEMA =`
is that every statement you execute is executed in new `sqlplus` process, so your session state is not saved between commands (DB connection is not persistent, but rather new connection is opened every time you execute the command).
I'll make the appropriate change to pull identifiers from all schemas, so they are available for completions.

**Comment by tkopets** [comment]
Prepared a new release with this improvement.

**Comment by calope** [comment]
Thank you very much!!!

**Comment by tkopets** [comment]
Let me know if the new version works as expected.
It may take several hours before new version will be available in PackageControl.

**Comment by calope** [comment]
Ok.

**Comment by calope** [comment]
It works great!!!

Several schema tables':

![captura de pantalla 2017-06-02 a las 14 42 28](https://cloud.githubusercontent.com/assets/5013300/26728366/e26ffc34-47a1-11e7-9447-330826e851e6.png)
