### ISSUE TITLE
Feature: Run file as script.

### ISSUE THREAD

**Issue by michaelwiller** [mtxr/SQLTools#114]
> This is a guideline to help us to understand SQLTools Issues. 
> 
> You don't need to stick to this, but please try to guide us to reproduce the errors or understand your feature requests.

### Issue Type

* [ X] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [X ] Are you running the latest version?
* [X ] Did you check the logs?
* [X ] Did you check the Setup?

### Description

I got SQLTools setup yesterday for Oracle. One thing that I do all the time is run a entire sql-file as a script. I use this for creating stored objects and some times for quick reports.

Is there a way to do this with SQLTools. If not, can you create one, please?

### Versions

- *Version*: v0.9.3
- *OS*:  Windows
- *RDBMS*: Oracle

**Comment by tkopets** [comment]
I think this would be a great addition to have a separate command to run the whole file.
I will implement this one when I have a bit more time.

**Comment by michaelwiller** [comment]
Great. Looking forward to it. Thanks.

**Comment by tkopets** [comment]
@michaelwiller 
This feature will be available in next release in a few days.

**Comment by tkopets** [comment]
New version released.
Try command `ST: Execute All File` or use default key-combination `ctrl+e ctrl+a`.

**Comment by michaelwiller** [comment]
@tkopets Checked. Working perfectly. Many, many thanks.

**Comment by tkopets** [comment]
Nice to hear that!
I will make a good use of this feature myself )

**Comment by michaelwiller** [comment]
I've begun setting up my utilities as well: https://github.com/michaelwiller/dev-command-utils/blob/master/sql-tools/README.md

Nothing much there, yet. But hey, I'm still on vacation :)

**Comment by tkopets** [comment]
Have a good rest!
Thanks for mentioning and promoting SQLTools!
