### ISSUE TITLE
Add views and columns views to oracle connection

### ISSUE THREAD

**Issue by calope** [mtxr/SQLTools#115]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

I have a proposal to include the views and view's column to oracle connection.

I have modified setting's file with this queries achieve the expected behavior:

```json
            "queries": {
                "desc" : {
                    "query": "select concat(concat(concat(concat('|', owner), '.'), table_name), '|') as tbls from all_tables UNION select concat(concat(concat(concat('|', owner), '.'), view_name), '|') as tbls from all_views;",
                    "options": ["-S"]
                },
                "columns": {
                    "query": "SELECT concat(concat(concat(concat('|', c.table_name), '.'), c.column_name), '|') AS cols FROM all_tab_columns c INNER JOIN all_tables t ON c.owner = t.owner AND c.table_name = t.table_name UNION SELECT concat(concat(concat(concat('|', c.table_name), '.'), c.column_name), '|') AS cols FROM all_tab_columns c INNER JOIN all_views t ON c.owner = t.owner AND c.table_name = t.view_name;",
                    "options": ["-S"]
                },
```

I would like to include this modifications to the base(master).

Thanks!

**Comment by mtxr** [comment]
Hi there!

Would you like to develop this feature? Otherwise it would take some time to develop it because I'm busy now.
