### ISSUE TITLE
Feature Request: List and Insert Saved Queries

### ISSUE THREAD

**Issue by Coteh** [mtxr/SQLTools#126]
### Issue Type

* [X] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Description

One small addition I think would be nice to have as well would be a command to insert a specified saved query into the current document. There are times at work for example when I have a bunch of test SQL commands on one file that I am working with and it would be nice to drop in another preformatted query I previously saved into the document without having to create a new tab. (If I were to open it using List and Open Saved Queries)

Let me know your thoughts on a feature such as this and if there's enough interest I can self-assign to this feature and add it in.

### Versions

- *Version*: v0.9.4
- *OS*: Windows 10 x64
- *RDBMS*: PostgreSQL

**Comment by tkopets** [comment]
I think this would be a nice addition to SQLTools.

**Comment by tkopets** [comment]
Thanks @Coteh !
I will prepare a new release with this new feature included in next few days.
