### ISSUE TITLE
Support for MS Access 

### ISSUE THREAD

**Issue by ilvetz** [mtxr/SQLTools#127]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

Would you consider adding support to MS Access databases, please?

**Comment by tkopets** [comment]
A quick googling revealed that it is simply not possible to add support for MS Access in SQLTools.
SQLTools utilizes command line interface (CLI) specific to each supported type of RDBMS.
For example:
* MySQL [mysql cli](https://dev.mysql.com/doc/refman/5.7/en/mysql.html)
* PostgreSQL [psql cli](https://www.postgresql.org/docs/current/static/app-psql.html)

And it appears that MS Access simply does not have one.
I'm closing this issue for now but if you have any suggestions or ideas how to implement it - feel free to reopen this issue with ideas or pull request.
