### ISSUE TITLE
Table description does not work when using SQLite 

### ISSUE THREAD

**Issue by ilvetz** [mtxr/SQLTools#128]
### Issue Type

* [ ] Feature Request
* [x] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

Using a SQLite DB, command _Table description_ shows the message "Your database has no table" but it currently does and list them when executing SQLite command `.tables`

### Steps to Reproduce (For bugfixes)

1. Connect to a populated SQLite database
2. Run Table Description command

**Expected behavior:**

Execution of .tables SQLite native command and presentation of the output

**Actual behavior:**

shows the message "Your database has no table"

### Versions

- *Version*: v0.9.4
- *OS*: Windows 7
- *RDBMS*: SQLite

**Comment by tkopets** [comment]
I've just tried to reproduce the issue, but all works fine for me.
I can list all tables, show table description, show table records.

Can you post your entire contents of `SQLTools.sublime-settings` in your Sublime `User` folder?
It could be that you have saved old versions of queries (these queries were changed not too long ago).
Try to remove all non-custom settings from your `SQLTools.sublime-settings` to see if that solves your problem.

**Comment by tkopets** [comment]
@ilvetz 
Any news on this issue?
Does it works for you after cleaning up the `SQLTools.sublime-settings` file?

**Comment by ilvetz** [comment]
Thank you @tkopets 

Sorry but I'm using the extension for the first time.
Now it works. I thought about some cached list of tables or a issue with single-table databases.

**Comment by tkopets** [comment]
No problem!
