### ISSUE TITLE
IBM DB2 support

### ISSUE THREAD

**Issue by darit** [mtxr/SQLTools#129]
### Issue Type

* [X] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Description

Add support for IBM DB2 please. This could be achieved using the JDBC connection.

**Comment by tkopets** [comment]
I will take a look into this one.
If DB2 has command line interface (CLI) and queryable tables metadata this can be done.

**Comment by tkopets** [comment]
I've looked into this and DB2 CLI is somewhat different compared to other RDBMS.
The main difference is that you cannot provide connection details upon invoking CLI from the command line, but only after the CLI is running and expecting commands.
I don't see an easy way to implement DB2 support at this time.
If you want, feel free to propose a pull request yourself.

**Comment by mtxr** [comment]
It seems to be out of SQLTools scope for now. I've been reading about DB2.

I'll be closing it, but @darit feel free to make pull request or reopen in case you think it fits.

Thanks!
