### ISSUE TITLE
Implement display of functions (for example using ctrl-e, ctrl-f)

### ISSUE THREAD

**Issue by rajanski** [mtxr/SQLTools#13]
Hi cool stuff this sqltools! I start to reallylike it,its so much quicker than PGADMIn3.

Anyhow, abovementioned feature would be real nice to have!

Cheers

**Comment by mtxr** [comment]
Hey! Thanks!

What excatly do you mean? A quick menu with all SQLTools functions?

**Comment by vectorien** [comment]
No I think what is meant to show a list of all the stored procedures (aka functions) in the database.

Like `select proname from pg_proc;`

Then on click on the function name, it should get the source of the function, as in `select proname,prosrc from pg_proc where proname= your_function_name;`

**Comment by mtxr** [comment]
Nice! I like it, I will study the other database server functions and implement that here.

Thanks!

**Comment by mtxr** [comment]
I guess it could also be added to auto complete. What do you think?

**Comment by vectorien** [comment]
sure

**Comment by tkopets** [comment]
Here is a starter query to get list of postgresql functions in format simmilar to one that is used to get list of tables:

```sql
SELECT DISTINCT
       '|' ||
       CASE WHEN n.nspname = current_schema()
            THEN quote_ident(f.proname)
            ELSE quote_ident(n.nspname)||'.'||quote_ident(f.proname)
       END || '|' AS funname
FROM pg_catalog.pg_proc AS f
     INNER JOIN pg_catalog.pg_namespace AS n ON n.oid = f.pronamespace
WHERE proisagg = false
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
ORDER BY 1;
```

Then you can use `\sf {function_name}` in `psql` to show function definition.

**Comment by mtxr** [comment]
Thanks @tkopets !

**Comment by tkopets** [comment]
Also to get functions into autocomplete list:

```sql
SELECT '|' ||
      CASE WHEN n.nspname = current_schema() 
           THEN quote_ident(f.proname)
           ELSE quote_ident(n.nspname)||'.'||quote_ident(f.proname)
      END ||
      '(' || pg_get_function_identity_arguments(f.oid) || ')' || '|' AS funname
FROM pg_catalog.pg_proc AS f INNER JOIN pg_catalog.pg_namespace AS n ON n.oid = f.pronamespace
WHERE proisagg = false AND n.nspname NOT IN ('pg_catalog', 'information_schema')
```

Use as a separate query, or just add it to existing query with columns list:
```sql
query_to_get_columns_autocomplete
UNION ALL
{^query_above^}
```

**Comment by mtxr** [comment]
Are you a python developer? Because if you would like, I can accept a pull-request from you :D

It would be amazing!

**Comment by tkopets** [comment]
Unfortunately, I'm not a python developer, but I can try to do it )

**Comment by mtxr** [comment]
Fixed and will be released tonight.
