### ISSUE TITLE
ssh tunnel connections

### ISSUE THREAD

**Issue by jairoGilC** [mtxr/SQLTools#131]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

Will be great if ssh tunnel connections was available for, for example connection to production DB

**Comment by mtxr** [comment]
Have you tried to create a bash script calling the ssh sgdb command?

I mean, something like:
```shellscript
#!/bin/bash
ssh user@server.com mysql $@
```

I've been using similar solution to run commands directly using a docker cli.

**Comment by mtxr** [comment]
@jairoGilC just let me know if it works for you.

**Comment by mtxr** [comment]
Closing due a lack of activity.
