### ISSUE TITLE
"ST: Setup Connections" does not exists

### ISSUE THREAD

**Issue by bilogic** [mtxr/SQLTools#139]
Hi,

SQLTools was installed using Package Control, but I'm unable to setup properly, below are some of the issues faced.

1. Using the Command Palette, ```ST: Setup Connections``` cannot be found. Thus cannot setup.

2. Going under ```Preferences```, ```Package Settings```, ```SQLTools```, all 3 options ```Connections```, ```Settings``` and ```Key Bindings``` are greyed out. Unable to create user settings from menu.

3. I tried creating my own config files, but docs show I had to provide a binary for mysql under ```cli```. Why is this necessary? I run sublime on windows, my mysql lives in linux.

Thank you.

**Comment by bilogic** [comment]
I understand #3 now, ```mysql.exe``` is used to open the connection to the remote database. Still figuring out how to get ```SQLTools``` to work.

**Comment by tkopets** [comment]
Can you please share what was the problem?

**Comment by bilogic** [comment]
My bad, the problem "```ST: Setup Connections``` does not exists" remains unsolved and likewise, the 3 options under ```SQLTools``` settings are still greyed.

However, there is a workaround to create my own config files. This was the reason why I closed the issue.

**Comment by tkopets** [comment]
Do you have a similar issue (greyed out package settings items) with other packages?

**Comment by bilogic** [comment]
No, I don't, the rest are fine.

**Comment by bilogic** [comment]
I'm trying out the latest ST3 build 3143 with only SQLTools, the 3 options are no longer greyed.
An observation is that: other packages do not open a new window with default and user settings side by side.

**Comment by tkopets** [comment]
Yes, indeed SQLTools uses some of the recently added Sublime Text API functionality.
Most probably that's why those menu items were disabled.

**Comment by bilogic** [comment]
Ok, it works now. Maybe you can add the ST3 minimum build required to your readme. Thank you.
