### ISSUE TITLE
Unable to execute mysql

### ISSUE THREAD

**Issue by bilogic** [mtxr/SQLTools#140]
1. I setup ```mysql.exe``` under the ```cli``` config
2. Tested ```mysql.exe``` to perform a remote connection in my command prompt, it can connect and query.
3. But running the same query in ST3 gives the following error in the console. Any idea why? (I'm not familiar with python)

```
Traceback (most recent call last):
  File "E:\sublimetext3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "E:\sublimetext3\Data\Packages\SQLTools\SQLTools.py", line 472, in run
    Window().status_message(MESSAGE_RUNNING_CMD)
AttributeError: 'Window' object has no attribute 'status_message'
```

Thank you.

**Comment by tkopets** [comment]
This is a very strange error you got there.
This code is supposed to work just fine.
Please try to restart Sublime Text and try again.
If fails, tell me your Sublime Text version and build number (Help -> About Sublime Text).

**Comment by bilogic** [comment]
Hi,

I have restarted ST3 and even tried to reinstall the SQLTools several times.
My ST3 version is Build 3084

**Comment by tkopets** [comment]
Can you try to update to newest Sublime Text version (build 3143) to see if this might be a problem?
Or this is not an option for you?
https://www.sublimetext.com/3

**Comment by bilogic** [comment]
Ok, it works now. Maybe you can add the ST3 minimum build required to your readme. Thank you.
