### ISSUE TITLE
Specify a different font size for output

### ISSUE THREAD

**Issue by bilogic** [mtxr/SQLTools#141]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [ ] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

Is it possible to specify a different fontsize for the output? Some of my tables are really wide due to long field names. Thank you.

**Comment by tkopets** [comment]
Last time I checked it was not possible to change font size for output panel separately from main font size.

**Comment by tkopets** [comment]
I mean Sublime does not offer this kind of functionality.

**Comment by bilogic** [comment]
Yes, I realized, but I tested something that worked in ST3 build 3143
https://stackoverflow.com/questions/15730547/sublime-text-2-how-to-change-the-font-size-of-the-output-panel
But it would mean directing your output to the console instead. 

Another post, which I did not test as unsure about SQLTools's class name
https://stackoverflow.com/questions/18288870/sublime-text-3-how-to-change-the-font-size-of-the-file-sidebar

**Comment by bilogic** [comment]
Another plugin which was able to style it's output https://github.com/aziz/PlainTasks (since styling is possible, I wonder about font size). Again, just suggestions. I'm out of the water with python. Thank you.

**Comment by tkopets** [comment]
Sublime Text console is the wrong place to output the results for queries for many reasons.
None of those plugins that you mentioned provide non-standard font size in output panels.
