### ISSUE TITLE
support aliases

### ISSUE THREAD

**Issue by swatoff** [mtxr/SQLTools#142]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Description

Alias from table name must associate with table name and columns.
If i type `select * from TABLE_NAME TN where TN.COLUMN1 is not null` codeintel must show all columns from alias TN

**Expected behavior:**

See description

**Actual behavior:**

Alias not working. Instead alias i need type a full table name

### Versions

- *Version*: all version
- *OS*: all OS
- *RDBMS*: all suppoer RDBMS

**Comment by tkopets** [comment]
Indeed looks like a bug - thanks for reporting it.
I will try to fix this bug this week.
For now, you can use lower-cased aliases (which hopefully should work as expected).
`select * from TABLE_NAME tn where tn.COLUMN1 is not null`

**Comment by swatoff** [comment]
Thank you, very much @tkopets. With lower-cased aliases work perfectly.

**Comment by tkopets** [comment]
This fix will be available in next release.
