### ISSUE TITLE
Show count for UPDATE

### ISSUE THREAD

**Issue by bilogic** [mtxr/SQLTools#148]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [x] Did you check the Setup?

### Description
Show number of lines updated after an UPDATE query is executed.
Currently, only something like the following is shown

```
/*
-- Executed querie(s) at 2017-10-21 18:16:53 took 0.217 s --
------------------------------------------------------------
UPDATE........................
------------------------------------------------------------
*/
```
Thank you.

### Steps to Reproduce (For bugfixes)

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions
- *Version*: v0.9.4

You can get this information from executing `ST: About` from Sublime `Command Palette`.

**Comment by tkopets** [comment]
This feature is related to specific DB CLI.
For example PostgreSQL `psql` DB CLI is showing this info by default, so I guess you are using MySQL.
For MySQL see related issue: #73 
It is not enabled by default in SQLTools as enabling verbose mode in MySQL also outputs the commands being executed which would spam the output with executed queries.

**Comment by bilogic** [comment]
ok got it. thanks!
