### ISSUE TITLE
ST Commands Do Not Appear In Command Palette

### ISSUE THREAD

**Issue by whong09** [mtxr/SQLTools#149]
### Issue Type

* [ ] Feature Request
* [ ] Bugfix/Errors
* [x] Questions
* [ ] Other

### Description

Hi I have installed SQLTools through Package Control

![image](https://user-images.githubusercontent.com/1329350/31920978-66ee867a-b821-11e7-9f7f-724aa48a569d.png)

However SQLTools commands are not appearing in command palette.

![image](https://user-images.githubusercontent.com/1329350/31920992-7e378c14-b821-11e7-934b-091dfc95ac49.png)

I am running Sublime Text 2 - Version 2.0.2 Build 2221 on Windows. What can I check to see why SQLTools is not working for me?

**Comment by tkopets** [comment]
SQLToos does not work with Sublime Text 2 (only Sublime Text 3).
