### ISSUE TITLE
For Cudatext

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/SQLTools#15]
Hi
I have text editor CudaText. You think possible to port addon to it? (I dont use SQL so i dont do it.)
Results of sql runs are impressive...

**Comment by mtxr** [comment]
For sure.

Just checked and it uses python based plugins so we could port it.
But I'm not familiarized with the editor so it would be easier if an user port the code.
I can help, generalize some classes for CudaText, but the integration with the editor would be difficult for me.

Are you interested? (Or do you know anyone who could help us?)

Regards,

M.

**Comment by Alexey-T** [comment]
I can do it; but on Linux no SQL engine here- how to test Sql execs?

**Comment by mtxr** [comment]
Try to install an SGDB like postgres, mysql, oracle etc.
I suggest you to try Mysql because it has a lot of information posted about it around the web.
After that, just, follow the instructions at code.mteixeira.me/SQLTools to setup the plugin :D 

If you want, we can have a hangouts about porting it.

**Comment by Alexey-T** [comment]
eh..That is complex.Maybe no time yet, so sorry (i can help with Cuda of course, if need)

**Comment by Alexey-T** [comment]
pls tell. I can make Cuda plugin with N items. 1) Exec sql, 2) ... 10)...
This ll be Py file `__init__.py`. empty def's. And you can open py file, add imports, add body for def's

Can we do it?

**Comment by Alexey-T** [comment]
Of course I ll add code which 1) shows menu for 2-3 items, 2) inserts 2-3 lines into editor

**Comment by mtxr** [comment]
I guess we can. 

Actually if you import the file SQLToolsModels.py to this __init__.py it should work.
This file is the one that manages connections, history and executions.
So you would just add the "Cuda" plugin api to your __init__.py calling the SQLToolsModels.

Is it ok?

**Comment by Alexey-T** [comment]
ye-ok; will post here Zip

- u open zip in Cuda, it shows propmt, u confirm
- u open py file in Cuda's "py" subdir (c:/cudatext/py/cuda_sql_tools)
- u edit it

**Comment by Alexey-T** [comment]
Zip; it gives NN items in Plugins/SQLTools; 2 items work :)     ..
[cuda_sql_tools.zip](https://github.com/mtxr/SQLTools/files/220232/cuda_sql_tools.zip)

**Comment by Alexey-T** [comment]
Cmd "config"/"config connectn" work now
(need reread json's then)
[cuda_sql_tools.zip](https://github.com/mtxr/SQLTools/files/220342/cuda_sql_tools.zip)

**Comment by Alexey-T** [comment]
Zip 
[cuda_sql_tools.zip](https://github.com/mtxr/SQLTools/files/220355/cuda_sql_tools.zip)

**Comment by Alexey-T** [comment]
So, what do you think about zip(it is not complete)?

**Comment by mtxr** [comment]
I couldn't see it completely yet. I'm a quite busy this week. :( But I'm promise to completely check on it on Saturday, is it ok?

I had some problems using cuda to test it (I'm not an user, sorry), but it seems right.
I was just confused because the SQLToolsModels.py is empty. I was expecting it to have some features working at least.

**Comment by Alexey-T** [comment]
It is ok; in end of week
(yep, SqlToolsModels empty; it needs porting)

**Comment by Alexey-T** [comment]
?

**Comment by mtxr** [comment]
Sorry mate, I'm in a hurry and couldn't spend time to fix the issues.

**Comment by mtxr** [comment]
I'll try to do it today, ok?

**Comment by Alexey-T** [comment]
It is okay

**Comment by mtxr** [comment]
I'm suffering with CudaText. It will take me more time, sorry buddy

**Comment by Alexey-T** [comment]
I see it is hard todo

**Comment by mtxr** [comment]
I just moved to a new company so I'm not having a lot of time to try it, sorry.
As I said, I can provide help, information and tips to someone who knows Cuda to develop it, but now I need to focus on my new job
