### ISSUE TITLE
Cuted symbols after $ symbol in table name

### ISSUE THREAD

**Issue by swatoff** [mtxr/SQLTools#152]
### Issue Type

* [ ] Feature Request
* [x] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [x] Did you check the Setup?

### Description

If table name contains special symbol, like a $, in sublime remains only symbols before $-symbol

### Steps to Reproduce (For bugfixes)

1. Type table name, like a RDB$DATABASE
2. Press CTRL+SPACE
3. In autocomplete window select table RDB$DATABASE
4. in sublime remains only symbols before $-symbol

### Versions

- *Version*: v0.9.6
- *OS*: all
- *RDBMS*: check on firebird

**Comment by swatoff** [comment]
![gif](https://user-images.githubusercontent.com/16893474/32278441-d3447594-bf26-11e7-86c9-5aefd1f63e26.gif)

**Comment by tkopets** [comment]
I will take a look into this.

**Comment by tkopets** [comment]
The fix will be available in next release.

**Comment by swatoff** [comment]
Thank you very much, @tkopets
