### ISSUE TITLE
Display number of records affected/found and other MySQL messages.

### ISSUE THREAD

**Issue by aditya43** [mtxr/SQLTools#159]
### Issue Type

Feature Request | Question

### Description

Would it be possible for us to see the MySQL responses after executing queries? 

For e.g.
After executing SELECT query, it should say [X] number of records found.
After executing INSERT/UPDATE/DELETE query, it should say [X] number of records affected.
After executing DDL queries (etc. CREATE/ALTER/RENAME/TRUNCATE/DROP TABLE etc.). it should render some response.

Thank you for a great plugin.

**Comment by tkopets** [comment]
See related issue: #73
It is not enabled by default in SQLTools as enabling verbose mode in MySQL also outputs the commands being executed which would spam the output.

**Comment by aditya43** [comment]
Thank you very much. That is exactly what I was looking for.
