### ISSUE TITLE
Use MyCLI as a command line.

### ISSUE THREAD

**Issue by aditya43** [mtxr/SQLTools#160]
### Issue Type

Feature Request

### Description

I'm using MyCLI command line for MySQL. It offers tons of great features like auto complete, syntax highlighting etc. Will it be possible to use MyCLI as a command line in SQLTools? It would be awesome if SQLTools can use auto complete suggestions and MySQL messages coming from MyCLI. Please take a look at this great tool : [https://www.mycli.net/](url)

**Comment by tkopets** [comment]
This is indeed a great tool CLI for MySQL, but it is simply impossible to use MyCLI for that purposes.
Sublime Text has its own internal mechanisms for displaying completions and highlighting (via syntax definition files).
If you think syntax highlighting can be improved, you can submit an issue to Sublime Packages project.
https://github.com/sublimehq/Packages/issues

SQLTools displays completions (with basic understanding of your current SQL text).
Take a look for more details on completions here: https://github.com/mtxr/SQLTools/issues/67#issuecomment-297849135

Please note that SQLTools supports multiple databases without introducing any database-specific code, so we simply cannot complete with MyCLI in that area.

**Comment by aditya43** [comment]
@tkopets thank you
