### ISSUE TITLE
'MySql' could not be found

### ISSUE THREAD

**Issue by ForestFDemo** [mtxr/SQLTools#166]
{
   "connections": {
        "demo": {
            "type"    : "mysql",
            "host"    : "127.0.0.1",
            "port"    : "3306",
            "username": "root",
            "password": "root",
            "database": "demo",
            "encoding": "utf-8"
        },
    },
    "default": "demo"
}

![image](https://user-images.githubusercontent.com/22193642/33720723-d526a216-db9f-11e7-84f4-97d96c73c422.png)

**Comment by tkopets** [comment]
Edit your SQLTools User Settings (`ST: Settings` or `Preferences`->`Package Settings`->`SQLTools`->`Settings`) and set the path to `mysql` binary.
Or alternatively add the folder where `mysql` binary is located to PATH (might not work on MacOS - see readme).
Here is an example of such config for Windows platform.

```json
{
	"cli":
	{
		"mysql": "c:/Program Files/MySQL/MySQL Server 5.7/bin/mysql.exe",
		"pgsql": "psql",
		"oracle": "sqlplus",
		"mssql": "sqlcmd",
		"firebird": "isql",
		"sqlite": "sqlite3",
		"sqsh": "sqsh"
	}
}
```

**Comment by ForestFDemo** [comment]
Thank you

**Comment by ForestFDemo** [comment]
But,Chinese garbled

![image](https://user-images.githubusercontent.com/22193642/33747317-49d3c80c-dbfd-11e7-8465-4775deda7850.png)


![image](https://user-images.githubusercontent.com/22193642/33747282-25f68000-dbfd-11e7-9c47-0effbdf599aa.png)

**Comment by tkopets** [comment]
The fix will be available in next release - in a next few days.

**Comment by ForestFDemo** [comment]
I use `utf8mb4` OK。
