### ISSUE TITLE
Nothing happen after install ant run command (any. ex show records for 'select 1;')

### ISSUE THREAD

**Issue by bisoff** [mtxr/SQLTools#17]
SQLTools v0.3.1: SQLTools.SQLTools loaded successfully
SQLTools v0.3.1: Default database set to Connection 1. Loading options and auto complete.
SQLTools v0.3.1: Usgin cli args psql -t --no-psqlrc -h 127.0.0.1 -p 5432 -U postgres -d postgres
..
Traceback (most recent call last):
  File "C:\Users\roman\AppData\Roaming\Sublime Text 3\Installed Packages\SQLTools.sublime-package\SQLToolsModels.py", line 293, in stop
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'c:\\users\\roman\\appdata\\local\\temp\\tmpyftt8f.sql'
 - ala Process can't access file becourse it locked by another process ..

tmpyftt8f.sql contents 'select 1;'

psql in PATH (in shell works)
sublime 3103
Win7 64
Postgres 9.5 (after install)

after reopen sublime - results same

{
  "connections": {
     "Connection 1": {
      "type"    : "pgsql",
      "host"    : "127.0.0.1",
      "port"    :  5432,
      "username": "postgres",
      "password": "<my password>",
      "database": "postgres",
      "encoding": "utf-8"
    }
  },
  "default": "Connection 1"
}

**Comment by mtxr** [comment]
Are you using a pgpass.conf file?

For connecting to PostgreSQL Database, you have to use a pgpass.conf file for connections using passwords. 
See PostgreSQL pgpass.conf documentation for more details. http://www.postgresql.org/docs/9.1/static/libpq-pgpass.html


I need to update the docs to tell users about it, But i'm in a hurry :(

**Comment by bisoff** [comment]
I don't use pgpass.conf with osx.
And sqltools working correctly. Not with Win7.
i seem it is file system prrblem (PermissionError: [WinError 32])

**Comment by mtxr** [comment]
I tried and tested a lot here using your description and after some testing, it worked!
But I used the pgpass file as described here:
https://www.postgresql.org/docs/9.1/static/libpq-pgpass.html
That was the only way I found to use it for now.

Could you try it, please?

I'll find a work around, but for now that's how I can help
