### ISSUE TITLE
self.query.encode(self.encoding) error since 0.9.8

### ISSUE THREAD

**Issue by optio** [mtxr/SQLTools#177]
### Issue Type
Bug/Error |

### Description

After today's update from SQLTools by PackageControl, I get this error when trying to perform a query using Postgresql:

Exception in thread Thread-43:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/home/sacha/.config/sublime-text-3/Packages/SQLTools/SQLToolsAPI/Command.py", line 92, in run
    results, errors = self.process.communicate(input=self.query.encode(self.encoding))
TypeError: encode() argument 1 must be str, not None

Same setup was working fine until yesterday so I'm 90% sure it's due to SQLTools update.

### Version

- *SQLTools Version*: v0.9.8
- *OS*:  Ubuntu 17.10
- *RDBMS*: PostgreSQL

**Comment by tkopets** [comment]
Sorry for breaking stuff )).
I will fix this today, meanwhile please make sure your connection has the encoding set (usually to `utf-8`).
I think that should solve your problem for now.
<pre>
{
  "connections": {
    "Connection PostgreSQL": {
      "type"    : "pgsql",
      "host"    : "127.0.0.1",
      "port"    :  5432,
      "database": "dbname",
      "username": "anotheruser",
      "password": "password",
      <b>"encoding": "utf-8"</b>
    }
  }
}
</pre>

**Comment by tkopets** [comment]
Should be fixed in the new release, which will be available via Package Control in a few hours.
Let me know if that works for you or reopen this issue.

**Comment by optio** [comment]
Fixed, Thanks!!!
