### ISSUE TITLE
No results can be seen if `INFO` statements show up

### ISSUE THREAD

**Issue by nightmarebadger** [mtxr/SQLTools#18]
First of all kudos on the development of this tool, makes my life easier :). 

I think I found a bug when running queries that will return some INFO statements. For instance, running this query:

```sql
select top 5 * from table1;
select top 5 * from table2;
```

Will work fine, showing both results one under the other, 5 rows each. Adding a line that produces an INFO statement **anywhere** in the script however ...

```sql
select top 5 * from table1;
drop table if exists nonexistent;
select top 5 * from table2;
```

Will only produce this:

```
INFO:  Table "nonexistent" does not exist and will be skipped
```

I guess the other lines still run (if they are more complex queries it still takes a while to run) but the results aren't visible anywhere. 

Cheers and keep up the good work!

**Comment by mtxr** [comment]
Which sgdb are you using?

**Comment by nightmarebadger** [comment]
Ah, that would be helpful information :P.

I am using `psql` to connect to an `Amazon Redshift` instance. 

```zsh
➜  ~  psql --version
psql (PostgreSQL) 9.5.2
```

**Comment by nightmarebadger** [comment]
Also the same thing happens when connecting to a local `PostgreSQL` instance, so the problem is not with `Amazon Redshift`. This does not happen when running the same query through SQLWorkbench.
