### ISSUE TITLE
After executing a query the cursor has its focus in the result windows and does not stay in the original place

### ISSUE THREAD

**Issue by matthiasmast** [mtxr/SQLTools#183]
Bug/Error

### Description

After executing a query the cursor has its focus in the result windows and does not stay in the original place. With this I need to use the mouse to set the cursor focus back to the original place to continue editing

### Version

- *SQLTools Version*: v0.9.9
- *OS*: Windows
- *RDBMS*: PostgreSQL

### Steps to Reproduce (For bugfixes)

1. Execute any query

**Expected behavior:** Cursor focus staying at the original place where it was before executing the query

**Actual behavior:** cursor focus jumped to the result window

**Comment by javidbu** [comment]
This also happens on Mac with MySQL. They added `Window().focus_view(resultContainer)` with the version 0.9.8, and I don't see the point on this. There should be a setting like `focus_on_result` so we can decide if it changes focus or not because it's really annoying
