### ISSUE TITLE
Possible to "stream" results instead of showing them all at once?

### ISSUE THREAD

**Issue by nightmarebadger** [mtxr/SQLTools#19]
Just an idea (useful when running slightly longer queries that produce intermediate results/logs/info) - would it be possible to directly open a new tab and start "streaming" into it (kinda like search does for instance) instead of waiting and showing the full thing at the end?

This would also make it more obvious that a search is running and is not done yet (again kinda like search, until you see a `query executed` message you know not everything is done yet).

**Comment by mtxr** [comment]
Nice. I'll think about it. I don't know if all SGDBs allows it but seems useful.

Do you have any idea?

**Comment by nightmarebadger** [comment]
About how to implement it in Sublime Text? No ideas here, sorry (I might take a look at it during the weekend if I get the chance though). 

It _should_ be possible though since tools like SQLWorkbench do it.

**Comment by mtxr** [comment]
I found a way of doing it. I'll start to work on it soon
