### ISSUE TITLE
Keep getting MySQL warning about using a password on the command line

### ISSUE THREAD

**Issue by rakista112** [mtxr/SQLTools#20]
When I try to SQL Execute any of my queries, it doesn't show me my resultset and I get this warning at the bottom. 

mysql: [Warning] Using a password on the command line interface can be insecure.

**Comment by mtxr** [comment]
That's an Mysql settings. You can work it around follwing the second answers here:
http://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-within-terminal-but-password-written

I'll create a fix to allow no password usage, but for now, please, could you try this solution?

**Comment by mtxr** [comment]
Did it work?

**Comment by rakista112** [comment]
I'll have to check it at work later. Thanks for the support :D
Sorry for the late reply

**Comment by naej56** [comment]
Hello,
i've the same issue.

How can i use --local-path=local with SQLTools ?
I already try in windows prompt and it work fine.
But not on SublimeText.

Thanks

**Comment by mtxr** [comment]
You can add this parameters to the your Sqltools.sublime settings.

Go to "Preferences" -> Package Settings -> SqlTools -> Default Settings.

You will see some options that are not in the docs.

![](https://s31.postimg.org/uzex50tuj/Screenshot_from_2016_07_30_14_43_06.png)

You can copy "cli_options" values and customize "args" param.

"args": "-h {host} -p {port} -U {username} -d {database} --local-path=local"

**Comment by naej56** [comment]
Hey with your help **it's working**
after many trie i found were put the `"--login-path=local"` 


I read again the manual of the MySQL command.
This part is the one that gave me the solution :

> The following groups are read: mysql client
The following options **may be given as the first argument**:
`--print-defaults           Print the program argument list and exit.`
`--no-defaults              Don't read default options from any option file, except for login file.`
`--defaults-file=#          Only read default options from the given file #.`
`--defaults-extra-file=#    Read this file after the global files are read.`
`--defaults-group-suffix=#  Also read groups with concat(group, suffix)`
`--login-path=#             Read this path from the login file.`

My SQLTools.sublime -settings file is like this

![sqltools sublime-setting](https://cloud.githubusercontent.com/assets/7542453/17273703/da839e6a-56be-11e6-9bff-c64a1918683d.jpg)

I retain only the **-D** for the database in **args**

Everything works except autocompletion, is there a key combination ?

**Comment by mtxr** [comment]
Nice!
I thought you were using psql. To be honest, auto completion should be working without any changes.
Could you try to check your sublime console to check if there is any errors?

Also, try to restart ST3 please.

**Comment by naej56** [comment]
Done restart ST3 and open the console and i get error.
I put a copy [on pastebin](http://pastebin.com/dK9HUA0b).

My list of installed packages :
- BracketHighlighter
- Color Highlighter
- ColorPicker
- Package Control
- Seti_UI
- SideBarEnhancements
- SQLTools
- SublimeCodeIntel
- Theme - Seti Monokai

I use ST3 Build 3114

**Comment by mtxr** [comment]
FIxed on the last commits
