### ISSUE TITLE
Mark somehow an empty result set

### ISSUE THREAD

**Issue by geerk** [mtxr/SQLTools#22]
Hi @mtxr, Thank you for great plugin!

Currently when query returns nothing we see the empty result page. And this is ambiguous whether we receive empty result of the query is still running or something went wrong.

Is it possible to display some special value for empty results? For example mysql client shows 
_Empty set (0.00 sec)_

**Comment by mtxr** [comment]
Ok buddy! It worth :D

**Comment by mtxr** [comment]
FIxed!
