### ISSUE TITLE
No results,only mysql warning

### ISSUE THREAD

**Issue by dongzhang1** [mtxr/SQLTools#23]
When I try to SQL Execute any of my queries, it doesn't show me my resultset and I get this warning at the bottom.
mysql: [Warning] Using a password on the command line interface can be insecure.

except ctrl+e+e,   other shortcut key do not work,why?

i tried another plugin SQL Exec,it works.it returns results  without warning and all shortcut key work.

thanks

**Comment by naej56** [comment]
Hello,

i've the same issue on a fresh install of SQLTools.
`Warning: Using a password on the command line interface can be insecure.`

>Version of softs :
>* Sublime Text : Build 3114.
>* MySQL : 5.6.20

I've search a little on google and this seem an explanation : 

> If your MySQL client/server version is a 5.6.x a way to avoid the WARNING message are using the mysql_config_editor tools:
>`mysql_config_editor set --login-path=local --host=localhost --user=username --password`
>Then you can use in your shell script:
>`mysql --login-path=local  -e "statement"`

[Source](http://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-within-terminal-but-password-written)

Hope that help you to solve the problem.

PS: sorry for my bad english.

**Comment by JoinBugs** [comment]
Hi @mtxr i believe that your plugin is awesome but i dont see some result when i execute a query, 
i open the sublime console and it show the follow:

SQLTools v0.3.1: SQLTools.SQLTools loaded successfully
SQLTools v0.3.1: Default database set to Connection 1. Loading options and auto complete.
SQLTools v0.3.1: Usgin cli args mysql -f --table -f --table --skip-column-names -h127.0.0.1 -P3306 -uroot -p -DMyDB
SQLTools v0.3.1: Usgin cli args mysql -f --table -f --table -h127.0.0.1 -P3306 -uroot -p -DMyDB
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2016-08-10 20:10:20, next run at 2016-08-10 21:10:20 or after
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLToolsModels.py", line 293, in stop
    os.unlink(self.tmp.name)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'c:\\users\\hp\\appdata\\local\\temp\\tmp2ud7_h.sql'
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLToolsModels.py", line 293, in stop
    os.unlink(self.tmp.name)

**Comment by mtxr** [comment]
@JoinBugs your problem has been fixed.
Could you try to update please?

**Comment by JoinBugs** [comment]
Thanks for your response@mtxr,
 I did that but now appear this....

### SQLTools v0.3.1: Query: SHOW TABLES </br>SQLTools v0.3.1:  Usgin cli args mysql -f --table -h127.0.0.1 -P3306 -uroot -p -DMyDB</br> SQLTools v0.3.1: Failed to remove tmp filec:\users\joinbugs\appdata\local\temp\tmpvm6x4g.sql

**Comment by mtxr** [comment]
But there results appeared, right?

**Comment by JoinBugs** [comment]
no, i can't see some result of my query

**Comment by mtxr** [comment]
Last tag just fixed it
