### ISSUE TITLE
SQLtools has problems with XAMPP

### ISSUE THREAD

**Issue by JoinBugs** [mtxr/SQLTools#27]
Hi again @mtxr,thanks so much for attend my problem, i find a problem with XAMPP, i have the following case, In three different computers, I installed the plugin SQlTools and this one can't bring the expect results and I got the message in console #23 and the same error for the others computers, but when i installed mysql from scratch i could see the result of my query.I'm sorry for my bad level english, my writting sucks.

**Comment by mtxr** [comment]
The last 2 versions are not using tmp files anymore, so I guess you just need to update
