### ISSUE TITLE
Update to sqlparse 0.2.1

### ISSUE THREAD

**Issue by vmuriart** [mtxr/SQLTools#29]
Noticed you are using an old version of sqlparse. The latest release address the python2/3 compatibility, so you will only need to keep one copy of the library.

It also fixes a few bugs, and adds alternate styles of formatting.

**Comment by vmuriart** [comment]
Possibly overkill, but you can take a look at how [pgcli](https://github.com/dbcli/pgcli) implemented table/column completion

**Comment by mtxr** [comment]
sqlparse is easy to change
pgcli I'll start studying to check how can I use/add some features here!

Thanks!

**Comment by mtxr** [comment]
Updated!
