### ISSUE TITLE
Cannot install a recent version of the plugin

### ISSUE THREAD

**Issue by geerk** [mtxr/SQLTools#30]
Hi @mtxr again. Thank you for your great work!

I have just tried to install recent version of the plugin but it appears I cannot do this for some reason. The first thing I tried is to remove it through Package Controll and install it again. When installed it shows v0.3.4 in the list of packages, but it actually logs v0.3.1 in the console. So I tried to remove plugin files manually - no luck. Then I tried to remove plugin, uninstall sublime text, then install it again and install the plugin - no luck. Here is a log from console on plugin installation after sublime text reinstallation: 

```
ignored packages updated to: ["SQLTools", "SublimeLinter", "SublimePythonIDE", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error parsing messages.json for SQLTools
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["SublimeLinter", "SublimePythonIDE", "Vintage"]
reloading plugin SQLTools.SQLTools
SQLTools v0.3.1: SQLTools.SQLTools loaded successfully
```

As you can see for some reason it logs v0.3.1 and new features are not available.

**Comment by mtxr** [comment]
You are using the latest version. I just forgot to bump it in the code
