### ISSUE TITLE
'mysql' could not be found by Sublime Text

### ISSUE THREAD

**Issue by bowlerhatsam** [mtxr/SQLTools#35]
When setting up connections, I get the following error:

'mysql could not be found by Sublime Text.
Please set the 'mysql' path in your SQLTools settings before continue.

I've followed through the basic installation and connection setup. Could further documentation be provided for setting this up?

**Comment by Alexey-T** [comment]
Executable file "mysql" is not found by OS, use PATH

**Comment by mtxr** [comment]
is it working?

**Comment by 441211324** [comment]
The key point is that the error message will prompt cli PATH for a problem, showing the configuration file path under windows, and now find the MySQL configuration file on the MAC machine，This the perfect solution。
PS: The point is to find your own MySQL PATH, don't copy mine, this is just a case
{
    "cli" : {
        "mysql"   : "/usr/local/opt/mysql@5.7/bin/mysql"
    }
}
