### ISSUE TITLE
Fix for Mac/Win

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/SQLTools#36]
we faced it in CudaText: all json files must be opened with `encoding='utf8'` parameter of `open`.
Mac has non utf8 codepage default, any cirylic chars saved on Linux- cannot read on Mac (from json)

**Comment by mtxr** [comment]
but open doesn't support encoding="utf-8" parameter. Does it?https://docs.python.org/2/library/functions.html#open

**Comment by Alexey-T** [comment]
It does it https://docs.python.org/3/library/functions.html#open
