### ISSUE TITLE
Sys.path?

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/SQLTools#37]
You had added dir of sqlparse to sys.path. Now its not OK; you have in one dir sqlparse + Utils.py + Log.py
Some plugins may do "import Log" and they get your custom Log import...

**Comment by mtxr** [comment]
Problem is that sqlparse is a python package and I need to use it locally. 

http://stackoverflow.com/questions/9059699/python-use-a-library-locally-instead-of-installing-it

As seem on StackOverflow, this is the "right" way of doing the sqlparse import cause' Sublime can't use pip to install packages

**Comment by Alexey-T** [comment]
but you may do better. Move sqlparse to "libs" subdir, add "libs" to path, so other files won't be in path with sqlparse.

**Comment by mtxr** [comment]
Fixed! Thanks!
