### ISSUE TITLE
getConnections error

### ISSUE THREAD

**Issue by Demetrio92** [mtxr/SQLTools#43]
Hello,

I've installed the package and set up a connection to my pgsql server. However I am unable to execute any query or generally get a responce from the plugin in its sql-clinet part. The formatting tool works just fine. 
I figured out, each call traces back the getConnection(). Here's the output of what happens if I try to execute simple `ST: Select Connection` from the command palette.

```
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "<somepath>\Portable\Sublime_Text_3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "<somepath>\Portable\Sublime_Text_3\Data\Packages\SQLTools\SQLTools.py", line 292, in run
    ST.selectConnection()
  File "<somepath>\Portable\Sublime_Text_3\Data\Packages\SQLTools\SQLTools.py", line 200, in selectConnection
    ST.connectionList = getConnections()
  File "<somepath>\Portable\Sublime_Text_3\Data\Packages\SQLTools\SQLTools.py", line 59, in getConnections
    options = connections.get('connections', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

Even though my `SQLToolsConnections.sublime-settings` has following:
```
{
    "connections": {
        "Connection 2": {
            "type"    : "pgsql",
            "host"    : "127.0.0.1",
            "port"    :  5432,
            "username": "anotheruser",
            "database": "dbname",
            "encoding": "utf-8"
        },
        "my_pgsql": {
            "type"    : "pgsql",
            "host"    : "<our_pgsql_server>",
            "port"    :  5432,
            "database": "<our_DB>",
            "username": "<my_username>",
            "password": "<my_password>",
            "encoding": "utf-8"
        },
    },
    "default": "my_pgsql"
}
```
The "Connection 2" is there just for test. Removing it does not solve the problem. 

Any Idea what may have caused the issue? 

p.s.
My config:
```
Win7
Sublime Text 3, Build 3126 (portable)
```

Python:
```
C:\Users\ME>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
```

**Comment by gc-alexlong** [comment]
Sounds like the same issue in #39.

**Comment by Demetrio92** [comment]
Half a day of debugging, and I figured the problem. The intial problem was that json.loads could not parse my connections settings file, which was due to a **one single trailing comma**!

Now I am out to fixing issue #41, since it poped out after I fixed this one.

**Comment by mtxr** [comment]
I'll be fixing it this weekend. Sorry guys!

**Comment by mtxr** [comment]
Fixed on last commit
