### ISSUE TITLE
How to disable the `SQLTools (v0.6.6): Logging is active` messages?

### ISSUE THREAD

**Issue by evandrocoan** [mtxr/SQLTools#46]
### How to disable the `SQLTools (v0.6.6): Logging is active` messages?

Are they intent to be printed or was forgot to disable them?

```
SQLTools (v0.6.6): Logging is active
SQLTools (v0.6.6): Connection timeout setted to 5000 seconds
SQLTools (v0.6.6): Connection history defined with max size 100
SQLTools (v0.6.6): SQLTools Loaded!
```

**Comment by mtxr** [comment]
Yeah. They should be printed, unless you set `debug` setting to `False`, ok?

You can disable it anytime, it's activated by default because we had some problems during sublime startup, It helped  a lot.
