### ISSUE TITLE
utf-8 problem

### ISSUE THREAD

**Issue by barrych** [mtxr/SQLTools#49]
I use MySql. 
DB Default collation is utf8_general_ci
DB charset is utf8

I don't see hebrew in the query results. (When using other tools - I see hebrew).
This is my settings - 
 "local": {         // Connection name, used in menu (Display name)
              "database" : "myDB",
              "host"     : "localhost",
              "port"     : "8889",
              "type"     : "mysql",    // SGDB to use: (mysql, pgsql, oracle, vertica)
              "username" : "myUsr",
              "password" : "myPwd" ,      // (if you are using postgresql, you must setup a pgpass file and set it to null)
              "encoding" : "utf-8"
          },

Is there something else I should do?

**Comment by mtxr** [comment]
Hi @barrych! 

I was searching for this issues and to be honest, this is the best answer I can do:
http://superuser.com/questions/257333/hebrew-utf8-characters-in-windows-cmd-console

We use MySQL cli to get the data, so as long as it has the issues, plugin will have it too.  Could you try to run some query on MySQL cli and give me the outputs? 

I will try to think about something to solve it, but for now that's a cli problem

**Comment by barrych** [comment]
Hi @mtxr ,
I am actually using mac and I see the hebrew characters in the terminal.

if I run the SQL in sublime I get this :
|   10007 | 10007 | Exclusive ?????????        | 3                | 3         | 3            | 3          | 3        | 3            | 3             |           3 | 3        | 3                 | 3                                  |   13617 | https://www.facebook.com/exclusive.lighting.furniture | NULL         | info@Exclusive.?????????        |      1 | NULL             | NULL        |


if I run it in MySql, I get this It is the same order, just the hebrew chars are RTL ...:
|   10007 | 10007 | Exclusive אקסקלוסיב          | 3           | 3         | 3            | 3          | 3        | 3            | 3             |           3 | 3        | 3                 | 3                |   13617 | https://www.facebook.com/exclusive.lighting.furniture | NULL         | info@Exclusive.אקסקלוסיב          |      1 | NULL     | NULL        |

Thanks.
