### ISSUE TITLE
Oracle : Sqlplus or cmd window displayed

### ISSUE THREAD

**Issue by Neospiro** [mtxr/SQLTools#5]
A "cmd" window is showed up when executing a query or selecting a server

Thank you :+1:

**Comment by mtxr** [comment]
I didn't understand it exactly. Could you describe more? Also a print screen could be helpful.

**Comment by AdrianLC** [comment]
OP is probably on Windows where subprocess open a black shell window by default. 
See http://stackoverflow.com/questions/7006238/how-do-i-hide-the-console-when-i-use-os-system-or-subprocess-call

**Comment by mtxr** [comment]
Thanks @AdrianLC. I will check it till tomorrow.

**Comment by mtxr** [comment]
I'm working in something.
