### ISSUE TITLE
character problem

### ISSUE THREAD

**Issue by 441211324** [mtxr/SQLTools#50]
select id,nickname from user limit 10;
ctrl+e,e

```
+--------+-----------------+
| id     | nickname        |
+--------+-----------------+
|      1 | laozhao         |
|    553 | yuegang         |
|   2304 | maodl           |
|   7282 | fxdfxq          |
| 102260 | majinyun        |
| 103898 | �ܳ���        | 周晨枫
| 104772 | kj_sso_e6in22lv |
| 104773 | student         |
| 104774 | kj_sso_6qscjyko |
| 104775 | kj_sso_1qnlo08k |
+--------+-----------------+
```
db  = utf-8
tb  = utf-8

my.ini
character-set-server=utf-8

A variety of attempts still have no effect,Is still garbled,There is no higher solution ?because the user's nickname in China can be a code-charset China  type

**Comment by 441211324** [comment]
```
"database@localhost": {
      "encoding": "utf-8"
 }


```
but still No Effect

**Comment by mtxr** [comment]
Can you try it: http://stackoverflow.com/questions/6787824/mysql-command-line-formatting-with-utf8
Add the param to your settings for mysql cli, please :)

Mysql cli should return as a utf8 encode.

**Comment by 441211324** [comment]
```
SET character_set_connection = utf8 ;
SET character_set_database = utf8 ; 
SET character_set_server = utf8 ; 
SET collation_server = utf8 ; 
SET collation_database = utf8 ;
SET character_set_client = utf8 ; 
SET character_set_results = utf8 ; 
SET collation_connection = utf8 ;
select * from user;

+--------+-----------------+
| id     | nickname        |
+--------+-----------------+
|      1 | laozhao         |
|    553 | yuegang         |
|   2304 | maodl           |
|   7282 | fxdfxq          |
| 102260 | majinyun        |
| 103898 | 周晨枫          | 
| 104772 | kj_sso_e6in22lv |
| 104773 | student         |
| 104774 | kj_sso_6qscjyko |
| 104775 | kj_sso_1qnlo08k |
+--------+-----------------+
```

 I found the problem, my.ini character_set_client can not come into force, can only be set before the implementation of the statement, I would like to have a configuration? After all, the development environment does not consider the performance issues, charset+sql implementation

Thank you very much, I have tried before, have ended in failure, and now is the right idea, thank you, sorry for English is not very good, with the translation software

**Comment by 441211324** [comment]
crux this tow sql together Play a role

```
SET character_set_results = utf8 ;
select * from user  limit 100;
```

**Comment by mtxr** [comment]
Yay!
 
You made it!

Would you like to write a "How to" about fixing this issue on mysql? Than we can start an Wiki about it. What do you think?

I'm closing it now, ok?

Thanks!

**Comment by 441211324** [comment]
Although my English level is limited, but this task I want to try, I write, you help me check, I will take the time to complete, I started this evening, it makes me full of passion.
