### ISSUE TITLE
MS SQL Server Support

### ISSUE THREAD

**Issue by jobe451** [mtxr/SQLTools#52]
I got SQLTools working with MS SQL Server, here is the definition I use. Maybe this could be added.

CLI-Definition:
```json
    "cli" : {
        "mssql"   : "sqlcmd"
    },
```

Calling sqlcmd definition:
```json
        "mssql": {
            "options": [],
            "before": [],
            "args": "-S \"{host}, {port}\" -U \"{username}\" -P \"{password}\" -d\"{database}\"",
            "queries": {
                "desc" : {
                    "query": "Select '| ' + Table_name + ' |' as tablenames From Information_schema.Tables Where Table_type = 'BASE TABLE' and Objectproperty (Object_id(Table_name), 'IsMsShipped') = 0",
                    "options": [],
                    "format" : "|%s|"
                },
                "desc table": {
                    "query": "SELECT ORDINAL_POSITION, cast(left(COLUMN_NAME,40) as varchar(40)) as COLUMN_NAME, cast(left(DATA_TYPE,20) as varchar(20)) as DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '%s'",
                    "options": [],
                    "format" : "|%s|"
                },
                "show records": {
                    "query": "select top 100 * from {0}",
                    "options": [],
                    "format" : "|%s|"
                }
            }
        },   
```

**Comment by llsousa** [comment]
`"args": "-S \"{host}, {port}\" -U \"{username}\" -P \"{password}\" -d\"{database}\"",`

@mtxr , in case the authentication is done by AD, there's no need to set username and password. Is there a way to define them as optional? 
Or, the code that calls the command test first if the parameters are null and in case they are, don't consider them?

**Comment by mtxr** [comment]
@llsousa sure. You can set it on your user settings by removing "username" and "password" params.

@jobe451 what was the error before these changes?

**Comment by jobe451** [comment]
@mtxr: There was no definition for MSSQL, the definition above adds that.

**Comment by mkormendy** [comment]
Is this implementation compatible for mac? Can I use this for my sqlcmd? [https://github.com/soheilpro/sqlcmd](https://github.com/soheilpro/sqlcmd)
