### ISSUE TITLE
Pix broken on website

### ISSUE THREAD

**Issue by jobe451** [mtxr/SQLTools#53]
Always when I access 
http://code.mteixeira.me/SQLTools/

All the pics are broken. Once I follow the link to github and then I go back to the website, the pics are shown as expected. 

At a first glance it seemed to me that SQLTools is unmaintained.

**Comment by mtxr** [comment]
This is cached data on you browser. Anyways I "touched" the images on cloud
flare to renew cache.

About maintenance, it's partially true. My current job takes me more time
now, so I just working on SQLTools during the weekends. I'm looking for
someone to help me

**Comment by mtxr** [comment]
Just tested it again and seems to be ok. I'm closing it.
