### ISSUE TITLE
Query Result is shown in different window than Query itself

### ISSUE THREAD

**Issue by matthiasmast** [mtxr/SQLTools#57]
Wenn running a SQL-Query with ctrl+e, ctrl+e and then changing the focus of the window the result is shown in the focused window instead of the window with the SQL-Query. Therefore when starting 2 queries at the same time from different windows the result of the first finished query will be overwritten by the second finished query.

**Comment by mtxr** [comment]
Try to use this option: `clear_output: false`.

It will append all results in the same window.

Queries shouldn't return the results in the same window than query. Some people run queries in the middle of the code.
