### ISSUE TITLE
Autocomplete for Mysql does not seem to be working

### ISSUE THREAD

**Issue by mrd05d** [mtxr/SQLTools#58]
Autocomplete for mysql does not work for me especially as shown in the demo. The only autocomplete that I get is just for words used in the local file. It would be super helpful to get the autocomplete for column names to work.

Thanks

Marcus Davis

**Comment by optio** [comment]
FYI Works fine for PostgreSQL

**Comment by mtxr** [comment]
Hello.

Does it still happening? Check please if you have any stack trace in your console.

**Comment by tkopets** [comment]
May be related to #61 and #67
