### ISSUE TITLE
Show the table name in the result of "ST: show table records" command.

### ISSUE THREAD

**Issue by ngr-t** [mtxr/SQLTools#63]
Currently the table name, whose records are taken by `ST: show table records` command, is not shown in the result (at least on Oracle DB). Isn't it helpful if it's shown somewhere above or below the records?

Anyway, thank you for the package. It helps me a lot!

**Comment by mtxr** [comment]
Actually, I can't do it 'cause i'm really busy. But It's a good feature. I'll work on it as soon as a have some time, ok?

Thanks!

**Comment by ngr-t** [comment]
I'd like to make a PR if you are so busy but you think it as a good feature.

**Comment by mtxr** [comment]
Please, feel free to do it, it will be really helpful.
