### ISSUE TITLE
Add "explain execution plan" command.

### ISSUE THREAD

**Issue by ngr-t** [mtxr/SQLTools#64]
Basically a DB has the feature to show the execution plan for a given query. I think it is sometimes helpful if we can show it without fixing the query into the one to get it. How do you think? 

Thanks,

**Comment by mtxr** [comment]
Actually, I can't do it 'cause i'm really busy. But It's a good feature. I'll work on it as soon as a have some time, ok?

Thanks!

**Comment by ngr-t** [comment]
I'd like to make a PR if you are so busy but you think it as a good feature.

**Comment by mtxr** [comment]
Please, feel free to do it, it will be really helpful.

**Comment by mtxr** [comment]
Resolved.
