### ISSUE TITLE
I'm Looking for help

### ISSUE THREAD

**Issue by mtxr** [mtxr/SQLTools#65]
Hey guys, I'm a quite busy now so I'm looking for you! Yes, you!

You developer that came here looking for help, I need you too.

Currently I have a full-time job and also my kid was born so I don't have enough time to keep this this package alone. 

Please, help us with pull requests and let's keep it evolving!

**Comment by optio** [comment]
Hi,

I've got 2 pull requests waiting for a merge (dont forget to bump version for packagecontrol!)

**Comment by mtxr** [comment]
Thanks! just did it
