### ISSUE TITLE
Unconfigured host being used

### ISSUE THREAD

**Issue by rpbaptist** [mtxr/SQLTools#66]
From my configuration:

```
         "Example": {
             "type"    : "mysql",
             "host"    : "127.0.0.1",
             "port"    : 3306,
             "username": "root",
             "password": null,
             "database": "example",
             "encoding": "utf-8"
         }
```

When executing a query:

`ERROR 1045 (28000): Access denied for user 'root'@'172.17.0.1' (using password: YES)`

I have no idea where host `172.17.0.1` is coming from.

**Comment by mtxr** [comment]
That's just your machine IP.

You can run Ipconfig (on windows) or ifconfig (on OSX or Linux).

The problem is that you are using password: null. With your connection doesn't have/need password, you should just remove this line like this:

```
         "Example": {
             "type"    : "mysql",
             "host"    : "127.0.0.1", // you can also use "localhost"
             "port"    : 3306,
             "username": "root"
             "database": "example",
             "encoding": "utf-8"
         }


```
