### ISSUE TITLE
update API vers to 0.2.6 or 0.3

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/SQLTools#69]
as it's changed, many lines new.

**Comment by tkopets** [comment]
Can you please explain in more detail?
Which API are you referring to?

**Comment by Alexey-T** [comment]
I mean API folder which is uused by plugin--
https://github.com/mtxr/SQLTools/tree/master/SQLToolsAPI
it has its version

**Comment by mtxr** [comment]
@tkopets we have a port for Cuda text editor. 
@Alexey-T I will update it soon, ok?

Thanks for remembering.

**Comment by mtxr** [comment]
The API is now using Sublime Text API inside of it, so it won't be fixed/update soon at CudaText.

This issue should now be opened at CudaText SQLTools repository.

Closing.
