### ISSUE TITLE
I keep getting "You need to setup your connections first"

### ISSUE THREAD

**Issue by Anachron** [mtxr/SQLTools#7]
... even though I've added the correct connection details into my user-prefs-file based on the github page.
I've also added the default connection info. I am on build 3103.

**Comment by mtxr** [comment]
You should use `SQLToolsConnections.sublime-settings` file instead of your User settings.

You can reach this file using your `Packages` menu, searching for SQLtools connections (in your packages)

I'm on my cellphone now, but I will describe it better in the project website.

Tell me if it works.

Regards,
Matheus.

**Comment by mtxr** [comment]
Preferences->package settings->SQLtools->SQL tools connections.

;)

**Comment by Anachron** [comment]
Wow, I am so blind! Yep, editing that file works. Thanks!

Maybe point it out in the docs somewhere. :+1:

**Comment by mtxr** [comment]
Yeah. I was reading here  and it could BW better written to be explicit.

Thanks mate! Hope you enjoy the plugin.
If you like, give it a star please ;)

**Comment by Anachron** [comment]
@mtxr I already gave it a star. It's a pretty neat :package: ! Thanks for your hard work.

**Comment by liuxthu** [comment]
my SQLtools connections is invalid, i can do nothing with it. is there something wrong with it?

**Comment by tkopets** [comment]
@liuxthu most probably you have a JSON syntax error in your connections file. Make sure your connections file contains a valid JSON.

**Comment by liuxthu** [comment]
> @liuxthu most probably you have a JSON syntax error in your connections file. Make sure your connections file contains a valid JSON.

![image](https://user-images.githubusercontent.com/42267487/47598513-31194f00-d9cf-11e8-85e4-f290c3f63eab.png)

dear sir, in my tools, these options cannot be seleced at all. i have no idea with it

**Comment by tkopets** [comment]
Upgrading to the latest Sublime version most likely will solve your
problem.

**Comment by Leonardorossato** [comment]
Ainda aparece essa mensagem : "you need to setup your configuration first" sublime text
