### ISSUE TITLE
How to get the DML affected rows?

### ISSUE THREAD

**Issue by MxJ24** [mtxr/SQLTools#73]
Can we put out the number of affected rows into the panel?

**Comment by tkopets** [comment]
What RDMBS are you using?

For example, when using PostgreSQL you get this kind of output already (`psql` feature).
e.g. running statements below:
```
create table a ( a int );
insert into a values (1);
insert into a values (2);
update a set a=a;
```
produces this output:
```
CREATE TABLE
INSERT 0 1
INSERT 0 1
UPDATE 2
```

**Comment by MxJ24** [comment]
MySQL 5.6, I tried with my test database, this plugin don't return the affacted rows, but the mysql command in terminal do.
Thanks.

**Comment by tkopets** [comment]
@MxJ24 
Passing `--verbose` or '-v' several times to `mysql` command line interface shows the number of affected rows, but it also outputs the query that was executed as well (see sample output below).
I couldn't find a way how to display the number of affected rows without printing the query that was executed.
This is a somewhat spammy output, so I don't think it is a good idea to enable it by default for all users, especially given the fact that those queries may be lengthy.

Sample
Input:
```
SELECT *
FROM a;
```

Output:
```
--------------
SELECT *
FROM a
--------------

+------+
| a    |
+------+
|    1 |
|    2 |
+------+
2 rows in set (0.00 sec)

Bye
```

If you want this kind of functionality as above, add the block below to your `SQLTools.sublime-settings` file in ST Users folder.
```json
{
    "cli_options": {
        "mysql": {
            "options": ["-f", "--table", "-v", "-v", "-v"]
        }
    }
}
```
