### ISSUE TITLE
Changing the setting "thread_timeout" has no effect

### ISSUE THREAD

**Issue by tkopets** [mtxr/SQLTools#79]
Changing the setting `thread_timeout` does not kill the underlying RDBMS querying process after "thread_timeout" seconds has passed, a hardcoded timeout of `5000` seconds is used instead.
https://github.com/mtxr/SQLTools/blob/9b049ef08eae204bbedcf0c8b370e5648b3d230a/SQLToolsAPI/Command.py#L11

**Comment by tkopets** [comment]
Additionally, the code to kill the process on Windows does not work for some reason, but works fine on Mac.

**Comment by pancodia** [comment]
I found the `thread_timeout` still takes no effect. Though now the timeout is 15 seconds.
