### ISSUE TITLE
Consider reducing the default setting for "thread_timeout"

### ISSUE THREAD

**Issue by tkopets** [mtxr/SQLTools#80]
The default setting for `thread_timeout` is currently set to 5000 seconds (~83 minutes), which I think way too much for someone to wait for query results, especially given the fact there is no feedback on query progress. 

I think a reasonable default setting would be somewhere in 30 to 60 seconds range.
@mtxr Your thoughts on this?

**Comment by mtxr** [comment]
The idea was to have this time as a milisecond, so five seconds. But I made a mistake and used it as seconds. I think its time to fix it, but in my opinion 15 sec is ok as default. 30 seconds is something that maybe just BigData users will use

**Comment by tkopets** [comment]
Thanks for the feedback.
I'll set it to 15 seconds then, as 5 seconds may be way too low.
