### ISSUE TITLE
Default key binding for st_select_connection doesn't work in MacOS

### ISSUE THREAD

**Issue by tompollard** [mtxr/SQLTools#83]
Love this package...thanks for sharing it. Minor issue, but for me the default key binding for changing the database connection doesn't work in MacOS (hitting the keys has no visible effect).

I'm running Sublime 3 (Build 3126)  on MacOS (Version 10.12.5 Beta).  I have tested the same bindings on a linux system and they work as expected.

The default key binding for changing the database connection is:

```
{ "keys": ["ctrl+alt+e"], "command": "st_select_connection" }
```

For now, I'm just overriding this with the following user setting:

```
{ "keys": ["ctrl+e", "ctrl+c"], "command": "st_select_connection" }
```

**Comment by tkopets** [comment]
Thanks for your feedback!
New default key combination is:
```json
{ "keys": ["ctrl+super+e"], "command": "st_select_connection" }
```
which would be: Ctrl+Cmd+e

Fix will be available in next release.

**Comment by tompollard** [comment]
Great, thanks again.

**Comment by mtxr** [comment]
Thanks Taras! Are you able to create tags?

**Comment by tkopets** [comment]
@mtxr
Sure, I can.
I will create one.

I have a question regarding new tags/releases of SQLTools:
Is there anything you have to update codewise (except documentation) each time you do a new tag/release?

E.g.
Do I need to update [version in SQLTools.py](https://github.com/mtxr/SQLTools/blob/6cfd03fa6ec56b6314cb4a9af3b9ff17942d523b/SQLTools.py#L1) to match latest tag ?
Right now we have:
```python
__version__ = "v0.6.7"
```  

Or anything else that comes to your mind related to releases/tags?

Also what tool you have used to create animated gifs as seen in the readme?

**Comment by mtxr** [comment]
Sure, needs update there.

The tool I used was a python script I found once (used on ubuntu, now I
switched to a new OS), it doesn't come to my mind now. But you can use any
tool you want, no restrictions.

I will create a Contribute.md file to help people develop and make a pull
request soon, than we can put some info there

**Comment by tkopets** [comment]
Thanks!
It would be great to have Contribution notice!
