### ISSUE TITLE
Issue in windows when select connection

### ISSUE THREAD

**Issue by sayasuhendra** [mtxr/SQLTools#9]
i got this in console

```python
  File "C:\Users\Suhendra\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLToolsModels.py", line 194, in builArgs
    args = args + ' '.join(cliOptions['options'])
TypeError: can only concatenate list (not "str") to list
```

mysql is in my path

**Comment by sayasuhendra** [comment]
I have set my connection

{
	 "connections": {
	     "Local dbname": {
	         "type"    : "mysql",
	         "host"    : "127.0.0.1",
	         "port"    : 3306,
	         "username": "user",
	         "password": "password",
	         "database": "dbname",
	         "encoding": "utf-8"
	     },
	     "Local dbname 4G": {
	         "type"    : "mysql",
	         "host"    : "127.0.0.1",
	         "port"    : 3306,
	         "username": "user",
	         "password": "password",
	         "database": "dbname4g",
	         "encoding": "utf-8"
	     }
	 },
	 "default": "Local dbname"
}

**Comment by fvelcker** [comment]
Hello,

Same issue here when I execute a query.

**Comment by mtxr** [comment]
I'm fixing it. Probably tomorrow will be all the opened issues closed and fixed

**Comment by sayasuhendra** [comment]
![sqltools still error](https://cloud.githubusercontent.com/assets/4870292/13871750/44fdae82-ed17-11e5-97af-d9444f323b80.PNG)
still error

**Comment by sayasuhendra** [comment]
I'm SQLExec user and I never get error like this. I'm interesting with your packages. because you provided more feature than sqlexec. But I never get SQLTools running well in my sublime. Thanks for your effort and response. I'm sorry I can't give good advice. We hope you can solve all issue. May be you can try to adopt some of SQLExec script. Good luck.

**Comment by mtxr** [comment]
try to set your mysql cli full path in settings please. It might work.

About sqlexec. I tryed that, but the old way (using a background shell supporting your cli) doesn't allow me to kill the thread. That's why even if your cli is your path it can't get it started.

I'll redo the docs to create a step-by-step install for windows and OSX.

I hope you can get ir working.

Thanks.
